site_name: Tutoriais & Ferramentas

nav:
  - Início: index.md
  - Tutoriais:
    - Linux: linux.md
    - Docker: docker.md
    - SQL: mysql.md
    - MkDocs: mkdocs.md
    - GIT: git.md
    - JavaScript: javascript.md
    - ADB: adb.md
  - Ferramentas: tools.md

theme:
  name: 'material'
  palette:
    scheme: 'slate'
  features:
    - content.code.copy
    # - navigation.tabs
    - toc.number

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  