site_name: Documentação KORE BRASIL

nav:
  - Início: index.md
  - Rotinas:
    - Billing: billing.md 
    - Faturamento: faturamento.md
    - Outras Rotinas: rotinas.md
  - Tutoriais:
    - Linux: linux.md
    - Docker: docker.md
    - SQL: mysql.md
    - MkDocs: mkdocs.md
    - GIT: git.md
    - ADB: adb.md
  - About: about.md

theme:
  name: 'material'
  palette:
    scheme: 'slate'
  features:
    - content.code.copy
    # - navigation.tabs
    - toc.number

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  