name: Continuous Improvement

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Atualizar o Git
      run: |
        sudo apt-get update
        sudo apt-get install git

    - name: Instalar o Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Construir o site
      run: mkdocs build

    - name: Deploy no GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./site
